### ISSUE TITLE
Use with new Rust

### ISSUE THREAD

**Issue by kirkins** [steveklabnik/adventure#2]
I'm trying to make this work the new version of rust. 

https://github.com/kirkins/adventure/commit/80c60aaacf1b50deb3698f7f4865bdf9094fd24a

I made some changes which fixed the initial errors but now I'm getting `this is an unreachable pattern` for each instance of these:

    north => println!("* Go (n)orth"),
    east  => println!("* Go (e)ast"),
    south => println!("* Go (s)outh"),
    west => println!("* Go (w)est"),

Any idea of what else I need to change?

**Comment by steveklabnik** [comment]
I have no idea, I haven't thought about this in two years 😄 

those can't be https://github.com/steveklabnik/adventure/blob/master/src/main.rs#L74-L77 any more, they must be literally in the match.

i can't see anything else obviously wrong.

you might also be interested in https://github.com/steveklabnik/ludum

**Comment by kirkins** [comment]
I will check it out :) 

I'd like to try to fix this as a challenge to myself. I just started the rust book yesterday and immediately searched for rust text adventure games!

**Comment by steveklabnik** [comment]
Great! If you send me a PR, I'm happy to merge it so that future travellers also can see a working version 😄

**Comment by steveklabnik** [comment]
Fixed by #4
